trigger:
  - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

stages:
- stage: CI
  jobs:
    - job: Build
      steps:
        - task: UseDotNet@2
          inputs:
            version: '8.0.x'

        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: 'Test'
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'

- stage: CD
  dependsOn: CI          # ← тільки якщо CI пройшов!
  condition: succeeded() # ← якщо тести провалились → стоп
  jobs:
    - job: Deploy
      steps:
        - script: |
            npm install -g @railway/cli
            railway up --service testwebapp
          env:
            RAILWAY_TOKEN: $(RAILWAY_TOKEN)
          displayName: 'Deploy to Railway'